#33 - Added PathPrefixSlice
artipie/http-client pull request #54
Opened 2020-09-30 15:00 UTC by olegmoz

Part of #33 
Added `PathPrefixSlice`

2020-09-30 17:49 UTC, olenagerasimova requested changes
@olegmoz added two suggestions, please, take a look

2020-09-30 17:49 UTC, olenagerasimova commented on src/main/java/com/artipie/http/client/PathPrefixSlice.java
> +                    .setPath(String.format("%s%s", this.prefix, uri.getPath()))
@olegmoz hm, I do not quite understand why create `URIBuilder` from original `uri` and then call `setPath`... Why cannot we simply call `URI.create(String.format("%s%s", this.prefix, uri.getPath()))` and inline `uri` variable?

2020-09-30 17:49 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/PathPrefixSliceTest.java
> +            new RequestLine(method, "/path").toString(),
@olegmoz I'd suggest to parametrize this test with different paths and prefixes: at least add complex path and prefix and `/` path

2020-10-01 07:16 UTC, olegmoz commented on src/main/java/com/artipie/http/client/PathPrefixSlice.java
> +                    .setPath(String.format("%s%s", this.prefix, uri.getPath()))
@olegmoz generally URI may contain host and port for proxy requests, but we do not really support it anyway. So I will simplify it, thanks

2020-10-01 07:22 UTC, olegmoz commented on src/main/java/com/artipie/http/client/PathPrefixSlice.java
> +                    .setPath(String.format("%s%s", this.prefix, uri.getPath()))
@olenagerasimova jsut understood that there is other reason actually! we need to preserve query as well, so I guess `new URIBuilder(uri)` should be preserved

2020-10-01 07:47 UTC, olegmoz commented
@olenagerasimova thanks to your comments I understood that there is no support for query in this class which is needed. So I supported query and improved tests, please review

2020-10-01 08:46 UTC, olenagerasimova approved these changes
@olegmoz thanks, looks good to merge

2020-10-01 08:55 UTC, merged