#50 - AuthClientSlice added
artipie/http-client pull request #55
Opened 2020-10-01 11:49 UTC by olegmoz

Part of #50 
`AuthClientSlice` added

2020-10-01 16:15 UTC, olenagerasimova requested changes
@olegmoz just cosmetic comments, take a look please

2020-10-01 16:15 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
> +        capture = new AtomicReference<>();
@olegmoz looks like these two lines can be inlined

2020-10-01 16:15 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
> +        capture = new AtomicReference<>();
@olegmoz same here

2020-10-02 06:16 UTC, olegmoz commented on src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
> +        capture = new AtomicReference<>();
@olenagerasimova I did it on purpose, line `final AtomicReference<Iterable<Map.Entry<String, String>>> capture = new AtomicReference<>();` is too long

2020-10-02 07:01 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
> +        capture = new AtomicReference<>();
@olegmoz hm, ok

2020-10-02 07:01 UTC, olenagerasimova approved these changes
@olegmoz good to merge

2020-10-02 07:32 UTC, merged