#51 - Added BearerAuthenticator
artipie/http-client pull request #65
Opened 2020-10-08 12:20 UTC by olegmoz

Part of #51 
Added `BearerAuthenticator`

2020-10-08 16:14 UTC, olenagerasimova requested changes
@olegmoz two suggestions, please, take a look

2020-10-08 16:14 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/auth/BearerAuthenticatorTest.java
> +            new IsEqual<>("/get_token")
@olegmoz I'd suggest to extract all the items being checked here into variables: host, post and path and use them in `WwwAuthenticate` ctor and in the assertions

2020-10-08 16:14 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/auth/BearerAuthenticatorTest.java
> +    void shouldProduceBearerHeaderUsingTokenFormat() {
@olegmoz and in this method I'd suggest to extract `mF_9.B5f-4.1JqM` into variable

2020-10-09 05:44 UTC, olegmoz commented
@olenagerasimova thanks, made the improvements

2020-10-09 09:06 UTC, olenagerasimova approved these changes
@olegmoz thanks, looks good to merge

2020-10-09 09:23 UTC, merged