(#21) - Add tests for `trustAll`
artipie/http-client pull request #72
Opened 2021-12-12 14:55 UTC by andreoss

Per #22 
- Add more tests

2021-12-14 05:39 UTC, g4s8 requested changes
@andreoss thanks, please check my comments

2021-12-14 05:39 UTC, g4s8 commented on src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java
> +            )
You can use `Assertions.assertThrows` from Junit5 here:
```java
SSLException ex = Assertions.assertThrows(SSLException.class, () -> client.https(url).response(...));
```

2021-12-14 05:39 UTC, g4s8 commented on src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java
> +                new RsHasStatus(RsStatus.OK)
Checking status is confusing here: if we expect this code to fail with exception, why do we need this assertion?

2021-12-14 16:28 UTC, andreoss commented on src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java
> +                new RsHasStatus(RsStatus.OK)
@g4s8 Done.

2021-12-14 16:28 UTC, andreoss commented on src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java
> +            )
@g4s8 Done.

2021-12-15 14:47 UTC, g4s8 approved these changes
@andreoss thanks

2021-12-15 14:48 UTC, merged

2021-12-24 14:27 UTC, kirill-h5i commented
PR for #21