test: add tests for JettyClientSlice with HTTPS server
artipie/http-client pull request #73
Opened 2022-01-27 13:46 UTC by dgarus

Closes #9

2022-01-27 19:27 UTC, dgarus commented
@g4s8 hello!
The PR is ready to be reviewed.

2022-01-28 14:10 UTC, olenagerasimova requested changes
@dgarus thanks, please, check my comments

2022-01-28 14:10 UTC, olenagerasimova commented on src/test/java/com/artipie/http/client/jetty/JettyClientSliceSecureTest.java
> +                    .setPath("keystore")
I'd suggest to use `new TestResource("keystore").getPath()` here to obtain full path to "keystore"

2022-01-29 08:15 UTC, dgarus commented on pom.xml
> +      </testResource>
Yes, it may look strange, but it is correct))
[stackoverflow](https://stackoverflow.com/a/34750851/7568229)
Example: [takes](https://github.com/yegor256/takes/blob/90d4ce7648409ba1d16365b25df177a131712d43/pom.xml#L289)

2022-01-29 08:24 UTC, dgarus commented
@olenagerasimova hello!
I fixed your comments. 
Could you please have a look?

2022-01-31 06:28 UTC, olenagerasimova approved these changes
@dgarus thanks

2022-01-31 06:28 UTC, merged