chore: clean up README
artipie/http-client pull request #80
Opened 2022-06-21 11:43 UTC by Swizbiz

https://github.com/artipie/artipie/issues/1031

2022-06-21 14:53 UTC, olenagerasimova requested changes
@Swizbiz thanks, looks good, although I have comments, please, check

2022-06-21 14:53 UTC, olenagerasimova commented on README.md
>  <dependency>
I'd suggest to add link to https://github.com/artipie/http for words "HTTP module" in the sentence right after maven dep xml

2022-06-21 14:53 UTC, olenagerasimova commented on README.md
>  <dependency>
> Client module **IS** targeted to implement HTTP client on top of these abstractions

"is" is missing in this sentence

2022-06-21 14:53 UTC, olenagerasimova commented on README.md
>  <dependency>
> `ClientSlices` is **AN** entry point for usage of this module:

"an" is missing in this sentence

2022-06-22 07:37 UTC, Swizbiz commented
> @Swizbiz thanks, looks good, although I have comments, please, check

done

2022-06-22 08:09 UTC, dgarus submitted a review, later dismissed
LGTM

2022-06-22 08:26 UTC, olenagerasimova commented on README.md
> +- `ClientSlice` - is an `Slice` that sends request to remote TCP endpoint and returns
why "an"? Slice starts with consonant... "A" is transformed into "an" only if the word starts with vowel: an entry, an opportunity, but a pen, a slice, a connection...

2022-06-22 08:49 UTC, olenagerasimova approved these changes
@Swizbiz thanks

2022-06-22 08:49 UTC, merged